// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvW7FJCOuib8yijVBIv9l857mJRKuTHJ4',
    appId: '1:999915558851:web:e89f6aeb919acbd7bb8f76',
    messagingSenderId: '999915558851',
    projectId: 'lenstracker-62a56',
    authDomain: 'lenstracker-62a56.firebaseapp.com',
    storageBucket: 'lenstracker-62a56.appspot.com',
    measurementId: 'G-NMW93SQKD8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxFYVjnSDAqfYoqqxLQF1Hx0Q7bIuI9vA',
    appId: '1:999915558851:android:53557db2b23ae8dcbb8f76',
    messagingSenderId: '999915558851',
    projectId: 'lenstracker-62a56',
    storageBucket: 'lenstracker-62a56.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-pOgGJirWpc-Xk3zu10SW_3AXH4pmo0E',
    appId: '1:999915558851:ios:f73d3363f4b467e3bb8f76',
    messagingSenderId: '999915558851',
    projectId: 'lenstracker-62a56',
    storageBucket: 'lenstracker-62a56.appspot.com',
    iosClientId: '999915558851-et8v78mu3ojshv8ilf09p2im04m56dok.apps.googleusercontent.com',
    iosBundleId: 'com.example.lensTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-pOgGJirWpc-Xk3zu10SW_3AXH4pmo0E',
    appId: '1:999915558851:ios:f73d3363f4b467e3bb8f76',
    messagingSenderId: '999915558851',
    projectId: 'lenstracker-62a56',
    storageBucket: 'lenstracker-62a56.appspot.com',
    iosClientId: '999915558851-et8v78mu3ojshv8ilf09p2im04m56dok.apps.googleusercontent.com',
    iosBundleId: 'com.example.lensTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvW7FJCOuib8yijVBIv9l857mJRKuTHJ4',
    appId: '1:999915558851:web:22323776e0d6ac90bb8f76',
    messagingSenderId: '999915558851',
    projectId: 'lenstracker-62a56',
    authDomain: 'lenstracker-62a56.firebaseapp.com',
    storageBucket: 'lenstracker-62a56.appspot.com',
    measurementId: 'G-YBDHMFP2G8',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyCvW7FJCOuib8yijVBIv9l857mJRKuTHJ4',
    appId: '1:999915558851:web:18c80bb41f816cabbb8f76',
    messagingSenderId: '999915558851',
    projectId: 'lenstracker-62a56',
    authDomain: 'lenstracker-62a56.firebaseapp.com',
    storageBucket: 'lenstracker-62a56.appspot.com',
    measurementId: 'G-HHZ4V8Y7Q8',
  );
}
